language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
before_script:
  - psql -c 'create database "db/test_smart_city"; ' -U postgres
  - psql -U postgres -c "create extension postgis"
addons:
  postgresql: "9.6"
